ALTER TABLE "Profiles" ALTER COLUMN "CreatedAt" DROP NOT NULL;
ALTER TABLE "Profiles" ALTER COLUMN "UpdatedAt" DROP NOT NULL;

ALTER TABLE "Relations" ALTER COLUMN "CreatedAt" DROP NOT NULL;
ALTER TABLE "Relations" ALTER COLUMN "UpdatedAt" DROP NOT NULL;
